---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/packethost/metabot

steps:
- name: test
  pull: always
  image: golang:1.11-alpine
  commands:
  - apk --update add make git dep
  - make ci-test

- name: build
  pull: always
  image: golang:1.11-alpine
  commands:
  - apk --update add make git dep
  - make build-all

- name: publish-amd64
  pull: always
  image: plugins/docker
  settings:
    context: dist/
    dockerfile: Dockerfile.amd64
    password:
      from_secret: docker_password
    repo: packethost/metabot
    tags:
    - "${DRONE_COMMIT}-amd64"
    - latest-amd64
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

- name: publish-arm64
  pull: always
  image: plugins/docker
  settings:
    context: dist/
    dockerfile: Dockerfile.arm64
    password:
      from_secret: docker_password
    repo: packethost/metabot
    tags:
    - "${DRONE_COMMIT}-arm64"
    - latest-arm64
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

- name: manifest
  pull: always
  image: plugins/docker
  commands:
  - apk --update add curl
  - curl -sSLo /bin/manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64
  - chmod +x /bin/manifest-tool
  - set +x
  - "echo /bin/manifest-tool --username=***** --password=***** push from-args --platforms=linux/amd64,linux/arm64 --target=packethost/metabot:$DRONE_COMMIT --template=packethost/metabot-$DRONE_COMMIT-ARCH"
  - "/bin/manifest-tool --username=$PLUGIN_USERNAME --password=$PLUGIN_PASSWORD push from-args --platforms=linux/amd64,linux/arm64 --target=packethost/metabot:$DRONE_COMMIT --template=packethost/metabot-$DRONE_COMMIT-ARCH"
  - set -x
  - set +x
  - "echo /bin/manifest-tool --username=***** --password=***** push from-args --platforms=linux/amd64,linux/arm64 --target=packethost/metabot:latest --template=packethost/metabot:latest-ARCH"
  - "/bin/manifest-tool --username=$PLUGIN_USERNAME --password=$PLUGIN_PASSWORD push from-args --platforms=linux/amd64,linux/arm64 --target=packethost/metabot:latest --template=packethost/metabot:latest-ARCH"
  - set -x
  settings:
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

...
