---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/packethost/metabot

steps:
- name: test
  pull: always
  image: golang:1.11-alpine
  commands:
  - apk --update add make git dep
  - make ci-test

- name: build
  pull: always
  image: golang:1.11-alpine
  commands:
  - apk --update add make git dep
  - make build-all
  - git log -1 --format="%H" > .tags

- name: publish-amd64
  pull: always
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.amd64
    repo: packethost/metabot
    context: dist/
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

- name: publish-arm64
  pull: always
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.arm64
    repo: packethost/metabot
    context: dist/
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

