---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/packethost/metabot

steps:
- name: test
  pull: always
  image: golang:1.11-alpine
  commands:
  - apk --update add make git dep
  - make ci-test

- name: build
  pull: always
  image: golang:1.11-alpine
  commands:
  - apk --update add make git dep
  - make build-all

- name: publish-amd64
  pull: always
  image: plugins/docker
  settings:
    tags:
    - "${DRONE_COMMIT}-amd64"
    - "latest-amd64"
    dockerfile: Dockerfile.amd64
    repo: packethost/metabot
    context: dist/
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

- name: publish-arm64
  pull: always
  image: plugins/docker
  settings:
    tags:
    - "${DRONE_COMMIT}-arm64"
    - "latest-arm64"
    dockerfile: Dockerfile.arm64
    repo: packethost/metabot
    context: dist/
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

- name: manifest-hash
  image: plugins/manifest
  settings:
    target: "packethost/metabot:${DRONE_COMMIT}"
    template: "packethost/metabot:${DRONE_COMMIT}-ARCH"
    platforms:
      - linux/amd64
      - linux/arm64
    ignore_missing: true
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

- name: manifest-latest
  image: plugins/manifest
  settings:
    target: "packethost/metabot:latest"
    template: "packethost/metabot:latest-ARCH"
    platforms:
      - linux/amd64
      - linux/arm64
    ignore_missing: true
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request
