---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/packethost/metabot

steps:
- name: test
  pull: always
  image: golang:1.11-alpine
  commands:
  - apk --update add make git dep
  - make ci-test

- name: build
  pull: always
  image: golang:1.11-alpine
  commands:
  - apk --update add make git dep
  - make build-all

## git tagged and latest images

- name: publish-amd64
  pull: always
  image: plugins/docker
  settings:
    context: dist/
    dockerfile: Dockerfile.amd64
    password:
      from_secret: docker_password
    repo: packethost/metabot
    tags:
    - "${DRONE_COMMIT}-amd64"
    - latest-amd64
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

- name: publish-arm64
  pull: always
  image: plugins/docker
  settings:
    context: dist/
    dockerfile: Dockerfile.arm64
    password:
      from_secret: docker_password
    repo: packethost/metabot
    tags:
    - "${DRONE_COMMIT}-arm64"
    - latest-arm64
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

## manifests

- name: manifest-commit
  pull: always
  image: plugins/manifest
  settings:
    target: "packethost/metabot:${DRONE_COMMIT}"
    template: "packethost/metabot:${DRONE_COMMIT}-ARCH"
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

- name: manifest-latest
  pull: always
  image: plugins/manifest
  settings:
    target: packethost/metabot:latest
    template: packethost/metabot:latest-ARCH
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

## Releases

- name: release-amd64
  pull: always
  image: plugins/docker
  settings:
    context: dist/
    dockerfile: Dockerfile.amd64
    password:
      from_secret: docker_password
    repo: packethost/metabot
    tags:
    - "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: release-arm64
  pull: always
  image: plugins/docker
  settings:
    context: dist/
    dockerfile: Dockerfile.arm64
    password:
      from_secret: docker_password
    repo: packethost/metabot
    tags:
    - "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: release-manifest-commit
  pull: always
  image: plugins/manifest
  settings:
    target: "packethost/metabot:${DRONE_TAG}"
    template: "packethost/metabot:${DRONE_TAG}-ARCH"
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    username:
      from_secret: docker_username
  when:
    event:
      - tag
