FROM alpine:3.9 as certs

# needed for TLS
RUN apk --update add ca-certificates

FROM scratch
ARG BINARY=metabot
ARG ARCH=amd64
COPY --from=certs /etc/ssl/certs/ /etc/ssl/certs/
COPY bin/${BINARY}-${ARCH} ${BINARY}

ENTRYPOINT ["/metabot"]
